# .github/workflows/semgrep.yml
name: Semgrep
on: [push, pull_request]

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container: semgrep/semgrep:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          semgrep scan \
            --config=p/owasp-top-ten \
            --config=r2c-security-audit \
            --config=r2c-php \
            --sarif --output semgrep.sarif || true
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

