# .semgrep.yml
rules:
  - id: include-ready-packs      # ダミー
    patterns: []
    message: ""
    severity: INFO

include:
  - p/owasp-top-ten              # OSS 版の汎用 Top10
  - r2c-security-audit           # Pro の多言語 taint ルール
  - r2c-php                       # Pro の PHP 専用強化パック
