name: Semgrep

on: [push, pull_request]

permissions:
  contents: read
  security-events: write   # SARIF アップロードに必須

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # OSS + Pro の推奨ルールを一括指定
      - uses: semgrep/semgrep-action@v2
        with:
          config: |
            p/owasp-top-ten           # OSS 版
            r2c-security-audit        # Pro taint 全言語
            r2c-php                   # Pro PHP 強化パック
        continue-on-error: true       # 脆弱性で exit≠0 でも後続へ
